/**
 * High-resilience JSON repair and parser utility for LLM-generated payloads.
 * Handles:
 * - Bad escaped characters (\Delta, \mu, \s, \d, \P, LaTeX, Windows paths)
 * - Unescaped raw newlines/tabs inside string literals
 * - Unescaped inner quotes in HTML attributes
 * - Markdown code blocks and preamble/postamble text
 * - Trailing commas before } and ]
 * - Truncated / unclosed JSON objects and arrays
 * - Fallback regex-based field extractors
 */

/**
 * Repairs a malformed JSON string generated by an LLM so it can be parsed cleanly.
 */
export function repairJsonString(raw: string): string {
  if (!raw || typeof raw !== "string") return "{}";

  let str = raw.trim();

  // 1. Remove markdown code blocks if present
  if (str.includes("```")) {
    const mdMatch = str.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
    if (mdMatch && mdMatch[1]) {
      str = mdMatch[1].trim();
    } else {
      str = str.replace(/```(?:json)?/gi, "").replace(/```/g, "").trim();
    }
  }

  // 2. Extract outermost JSON structure
  const firstBrace = str.indexOf("{");
  const firstBracket = str.indexOf("[");
  let startIdx = -1;
  let isArray = false;

  if (firstBrace !== -1 && firstBracket !== -1) {
    if (firstBrace < firstBracket) {
      startIdx = firstBrace;
      isArray = false;
    } else {
      startIdx = firstBracket;
      isArray = true;
    }
  } else if (firstBrace !== -1) {
    startIdx = firstBrace;
    isArray = false;
  } else if (firstBracket !== -1) {
    startIdx = firstBracket;
    isArray = true;
  }

  if (startIdx !== -1) {
    const endChar = isArray ? "]" : "}";
    const lastEnd = str.lastIndexOf(endChar);
    if (lastEnd !== -1 && lastEnd >= startIdx) {
      str = str.substring(startIdx, lastEnd + 1);
    } else {
      str = str.substring(startIdx);
    }
  }

  // 3. First attempt at direct parse (fast path)
  try {
    JSON.parse(str);
    return str;
  } catch {
    // Proceed to robust character-level sanitization
  }

  // 4. Character-by-character scanner to sanitize strings:
  //    - Escapes invalid backslashes (e.g. \Delta, \mu, \s, \d, \P, \t not followed by valid escape)
  //    - Converts literal unescaped newlines/tabs inside strings to \n / \t
  let result = "";
  let inString = false;
  let isEscaped = false;

  for (let i = 0; i < str.length; i++) {
    const char = str[i];

    if (!inString) {
      if (char === '"') {
        inString = true;
        isEscaped = false;
        result += char;
      } else {
        result += char;
      }
    } else {
      // We are inside a JSON string literal
      if (isEscaped) {
        // The previous character was a backslash
        isEscaped = false;

        // Valid JSON escapes: " \ / b f n r t u
        if (
          char === '"' ||
          char === "\\" ||
          char === "/" ||
          char === "b" ||
          char === "f" ||
          char === "n" ||
          char === "r" ||
          char === "t"
        ) {
          result += char;
        } else if (char === "u") {
          // Check if followed by 4 hex digits
          const hex = str.substring(i + 1, i + 5);
          if (/^[0-9a-fA-F]{4}$/.test(hex)) {
            result += char;
          } else {
            // Invalid unicode escape -> duplicate backslash
            result += "\\u";
          }
        } else {
          // Bad escaped character (e.g. \m, \s, \d, \D, \a, \P, \., \ , etc.)
          // We preserve the backslash by doubling it, so \d becomes \\d
          result += "\\" + char;
        }
      } else {
        if (char === "\\") {
          isEscaped = true;
          result += char;
        } else if (char === '"') {
          inString = false;
          result += char;
        } else if (char === "\n") {
          result += "\\n";
        } else if (char === "\r") {
          result += "\\r";
        } else if (char === "\t") {
          result += "\\t";
        } else if (char.charCodeAt(0) < 32) {
          // Control character
          result += " ";
        } else {
          result += char;
        }
      }
    }
  }

  // If ended while still inside a string or with trailing unescaped backslash
  if (isEscaped) {
    result += "\\";
  }
  if (inString) {
    result += '"';
  }

  // 5. Remove trailing commas before closing braces/brackets
  result = result.replace(/,(\s*[}\]])/g, "$1");

  // 6. Balance unclosed brackets/braces if truncated
  let openBraces = 0;
  let openBrackets = 0;
  let insideStr = false;
  let esc = false;

  for (let i = 0; i < result.length; i++) {
    const c = result[i];
    if (esc) {
      esc = false;
      continue;
    }
    if (c === "\\") {
      esc = true;
      continue;
    }
    if (c === '"') {
      insideStr = !insideStr;
      continue;
    }
    if (!insideStr) {
      if (c === "{") openBraces++;
      else if (c === "}") openBraces = Math.max(0, openBraces - 1);
      else if (c === "[") openBrackets++;
      else if (c === "]") openBrackets = Math.max(0, openBrackets - 1);
    }
  }

  while (openBrackets > 0) {
    result += "]";
    openBrackets--;
  }
  while (openBraces > 0) {
    result += "}";
    openBraces--;
  }

  return result;
}

/**
 * Safely parses any JSON string from an LLM response.
 * If standard JSON.parse fails, applies repair algorithms and fallbacks.
 */
export function robustJsonParse<T = any>(rawText: string, fallbackValue?: T): T {
  if (!rawText || typeof rawText !== "string") {
    return (fallbackValue !== undefined ? fallbackValue : ({} as any)) as T;
  }

  // Attempt 1: Direct JSON.parse
  try {
    return JSON.parse(rawText.trim());
  } catch {}

  // Attempt 2: Repair and parse
  try {
    const repaired = repairJsonString(rawText);
    return JSON.parse(repaired);
  } catch (err1) {
    // Attempt 3: Aggressive clean (replace all stray single backslashes not in valid escapes)
    try {
      const aggressive = rawText
        .replace(/\\(?!["\\/bfnrt]|u[0-9a-fA-F]{4})/g, "\\\\")
        .replace(/[\n\r]/g, "\\n");
      const candidateMatch = aggressive.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
      if (candidateMatch) {
        return JSON.parse(candidateMatch[0]);
      }
    } catch {}

    // Attempt 4: Regex-based field extraction for SIGRE UD payloads
    try {
      const fallbackObj = extractSigreFieldsFromRawText(rawText);
      if (fallbackObj && Object.keys(fallbackObj).length > 0) {
        console.warn("Recovered SIGRE UD object via field extraction fallback.", err1);
        return fallbackObj as T;
      }
    } catch {}

    console.error("Failed to parse JSON even after robust repair:", err1, rawText.substring(0, 300));
    if (fallbackValue !== undefined) {
      return fallbackValue;
    }
    throw new Error(`Error en el formato de respuesta del modelo (JSON inválido): ${(err1 as Error)?.message || "Bad escape"}`);
  }
}

/**
 * Fallback field extractor for SIGRE UD objects in case LLM output was severely broken.
 */
function extractSigreFieldsFromRawText(text: string): Record<string, any> | null {
  const result: Record<string, any> = {};

  // Match key patterns like "titulo": "..." or "titulo": <value>
  const extractStringField = (key: string): string => {
    const reg = new RegExp(`"${key}"\\s*:\\s*"((?:[^"\\\\]|\\\\.)*)"`, "i");
    const m = text.match(reg);
    if (m && m[1]) {
      try {
        return JSON.parse(`"${m[1]}"`);
      } catch {
        return m[1].replace(/\\"/g, '"').replace(/\\n/g, "\n");
      }
    }
    return "";
  };

  const fields = [
    "titulo",
    "cotRazonamiento",
    "introduccion",
    "indiceDesarrollo",
    "desarrolloEpigrafesHtml",
    "glosarioHtml",
    "autoevaluacionHtml",
    "conclusiones",
    "relacionIntradisciplinar",
    "diagramaMermaid",
    "mapaMentalOpml",
    "bancoGiftParte1",
    "bancoGiftParte2",
    "propuestaExamenHtml",
    "solucionarioExamenHtml",
    "propuestaHdiConceptual",
    "vinculacionCurricularHtml",
    "matrizAlineacionHtml",
    "tablaActividadesHtml",
    "rubricasXml",
    "nombreApp",
    "prdMarkdown",
    "appHtmlCode",
    "justificacionPedagogica",
  ];

  let foundAny = false;
  for (const f of fields) {
    const val = extractStringField(f);
    if (val) {
      result[f] = val;
      foundAny = true;
    }
  }

  // Extract array for contenidos or objetivosSmart if present
  const objSmartMatch = text.match(/"objetivosSmart"\s*:\s*\[([\s\S]*?)\]/i);
  if (objSmartMatch && objSmartMatch[1]) {
    try {
      result["objetivosSmart"] = JSON.parse(`[${objSmartMatch[1]}]`);
      foundAny = true;
    } catch {
      result["objetivosSmart"] = objSmartMatch[1]
        .split(",")
        .map((s) => s.trim().replace(/^"|"$/g, ""))
        .filter(Boolean);
    }
  }

  return foundAny ? result : null;
}
